services:
  - type: web
    name: trashia-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: trashia-redis
          property: connectionString
    healthCheckPath: /health

  - type: redis
    name: trashia-redis
    region: oregon
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
